stages:
  - install
  - lint
  - build
  - e2e

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint:
  stage: lint
  image: node:20
  script:
    - npm run lint || true
  needs: [install]


build:
  stage: build
  image: node:20
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - www/
    expire_in: 1 week
  needs: [install]
  only:
    - main


e2e:
  stage: e2e
  image: cypress/included:13.6.0
  script:
    - npm run build -- --configuration=ci
    - npx cypress run
  needs: [install]
  only:
    - main