stages:
  - install
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint:
  stage: lint
  image: node:20
  script:
    - npm run lint
  needs: [install]

test:
  stage: test
  image: node:20
  script:
    - npm run test -- --configuration=ci
  needs: [install]

build:
  stage: build
  image: node:20
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - www/
    expire_in: 1 week
  needs: [install]
  only:
    - main
    - develop